name: test-environment
channels:
  - conda-forge
dependencies:
  - python=3.9
  - dask
  - pandas
  - pymongo
  - mongodb
  - pytest
  # Temporarily need dev version of distributed to use
  # @gen_cluster with pytest fixtures
  - pip
  - pip:
    - git+https://github.com/dask/distributed